/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sgpf.views.login;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import sgpf.daos.UsuarioDao;
import java.util.regex.Pattern;


/**
 *
 * @author Brayan Hurtado
 */
public class Registrar extends javax.swing.JFrame {

    /**
     * Creates new form Regiistrar
     */
    public Registrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InicioSesionFondo = new javax.swing.JPanel();
        InicioSesion = new javax.swing.JPanel();
        UsuarioIngresado = new javax.swing.JTextField();
        IngresarUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Identificacion = new javax.swing.JTextField();
        IngresarUsuario1 = new javax.swing.JLabel();
        Apellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Correo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BotonRegistrarse = new javax.swing.JButton();
        Contrasena = new javax.swing.JPasswordField();
        Icono_InicioSesion = new javax.swing.JLabel();
        Titulo_Registrarse = new javax.swing.JLabel();
        BotonRegistrarse2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InicioSesionFondo.setBackground(new java.awt.Color(100, 149, 237));
        InicioSesionFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InicioSesion.setBackground(new java.awt.Color(135, 206, 235));

        UsuarioIngresado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioIngresadoActionPerformed(evt);
            }
        });

        IngresarUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        IngresarUsuario.setText("Ingresa Nombres");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Ingresa Numero de Identificacion");

        Identificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdentificacionActionPerformed(evt);
            }
        });

        IngresarUsuario1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        IngresarUsuario1.setText("Ingresa Apellidos");

        Apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Ingresa Correo");

        Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Ingresa Contraseña");

        BotonRegistrarse.setBackground(new java.awt.Color(0, 191, 255));
        BotonRegistrarse.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BotonRegistrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgpf/resources/icons/icons8-registrarse-48.png"))); // NOI18N
        BotonRegistrarse.setText("Registrarse");
        BotonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarseActionPerformed(evt);
            }
        });

        Contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContrasenaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InicioSesionLayout = new javax.swing.GroupLayout(InicioSesion);
        InicioSesion.setLayout(InicioSesionLayout);
        InicioSesionLayout.setHorizontalGroup(
            InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioSesionLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonRegistrarse)
                    .addComponent(Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IngresarUsuario1)
                    .addComponent(jLabel4)
                    .addGroup(InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Contrasena)
                        .addComponent(Correo, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
                    .addGroup(InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addGroup(InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UsuarioIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(IngresarUsuario)
                                .addComponent(Identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(521, Short.MAX_VALUE))
        );
        InicioSesionLayout.setVerticalGroup(
            InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioSesionLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(IngresarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsuarioIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IngresarUsuario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonRegistrarse)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        InicioSesionFondo.add(InicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 600, 510));

        Icono_InicioSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgpf/resources/icons/registrar2.png"))); // NOI18N
        InicioSesionFondo.add(Icono_InicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 250, 250));

        Titulo_Registrarse.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Titulo_Registrarse.setForeground(new java.awt.Color(255, 255, 255));
        Titulo_Registrarse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo_Registrarse.setText("<html> <div style=\"text-align: center;\"> Registro de usuarios </div> </html>");
        InicioSesionFondo.add(Titulo_Registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 273, 88));

        BotonRegistrarse2.setBackground(new java.awt.Color(0, 191, 255));
        BotonRegistrarse2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BotonRegistrarse2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgpf/resources/icons/cerrar-sesion.png"))); // NOI18N
        BotonRegistrarse2.setText("Salir");
        BotonRegistrarse2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BotonRegistrarse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarse2ActionPerformed(evt);
            }
        });
        InicioSesionFondo.add(BotonRegistrarse2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InicioSesionFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InicioSesionFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioIngresadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioIngresadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioIngresadoActionPerformed

    private void IdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdentificacionActionPerformed

    private void BotonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarseActionPerformed
        String nombres = UsuarioIngresado.getText();
        String apellidos = Apellidos.getText();
        String identificacion = Identificacion.getText();
        String correo = Correo.getText();
        String contraseña = new String(Contrasena.getPassword()); // Convertir el texto del JPasswordField

        // Validar que ningún campo esté vacío
        if (nombres.isEmpty() || apellidos.isEmpty() || identificacion.isEmpty() 
                || correo.isEmpty() || contraseña.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!nombres.matches("[a-zA-ZáéíóúÁÉÍÓÚÑñ ]+")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Los nombres solo pueden contener letras y espacios.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!apellidos.matches("[a-zA-ZáéíóúÁÉÍÓÚÑñ ]+")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Los apellidos solo pueden contener letras y espacios.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!identificacion.matches("\\d+")) {  // \\d+ asegura que solo haya números
            javax.swing.JOptionPane.showMessageDialog(this, "La identificación solo puede contener números.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar formato del correo con una expresión regular
        if (!correo.matches("^[\\w._%+-]+@[\\w.-]+\\.[a-zA-Z]{2,}$")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingresa un correo válido.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if(!esContraseñaSegura(contraseña)){
            return;  
        }
        
        String contrasenaEncriptada = encriptarConSHA256(contraseña);

        
        // Limpia los campos después del registro
        UsuarioIngresado.setText("");
        Apellidos.setText("");
        Identificacion.setText("");
        Correo.setText("");
        Contrasena.setText("");
        
        UsuarioDao usuarioDAO = new UsuarioDao();
        boolean exito = usuarioDAO.registrarUsuario(nombres, apellidos, identificacion, correo, contrasenaEncriptada);

        if (exito) {
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario registrado con éxito en la base de datos.", "Registro Exitoso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            InicioSesion inicioSesion = new InicioSesion();
            inicioSesion.setVisible(true); 
            this.dispose(); 
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al registrar el usuario en la base de datos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonRegistrarseActionPerformed

    private void ApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidosActionPerformed

    private void CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoActionPerformed

    private void BotonRegistrarse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarse2ActionPerformed
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Estás seguro de que deseas salir?", 
            "Confirmar salida", 
            javax.swing.JOptionPane.YES_NO_OPTION, 
            javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
            InicioSesion inicioSesion = new InicioSesion();
            inicioSesion.setVisible(true); 
            this.dispose(); 
        }
    }//GEN-LAST:event_BotonRegistrarse2ActionPerformed

    private void ContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContrasenaActionPerformed

    public static boolean esContraseñaSegura(String contraseña) {
        // Verificar la longitud mínima
        if (contraseña.length() < 8) {
            javax.swing.JOptionPane.showMessageDialog(null, "La contraseña debe tener al menos 8 caracteres.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Verificar que tenga al menos una letra mayúscula
        if (!Pattern.compile("[A-Z]").matcher(contraseña).find()) {
            javax.swing.JOptionPane.showMessageDialog(null, "La contraseña debe contener al menos una letra mayúscula.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Verificar que tenga al menos una letra minúscula
        if (!Pattern.compile("[a-z]").matcher(contraseña).find()) {
            javax.swing.JOptionPane.showMessageDialog(null, "La contraseña debe contener al menos una letra minúscula.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Verificar que tenga al menos un número
        if (!Pattern.compile("[0-9]").matcher(contraseña).find()) {
            javax.swing.JOptionPane.showMessageDialog(null, "La contraseña debe contener al menos un número.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Verificar que tenga al menos un carácter especial
        if (!Pattern.compile("[@#$%^&+=!]").matcher(contraseña).find()) {
            javax.swing.JOptionPane.showMessageDialog(null, "La contraseña debe contener al menos un carácter especial (ej. @, #, $, %, ^, &, +, =).", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Verificar que no contenga espacios
        if (contraseña.contains(" ")) {
            javax.swing.JOptionPane.showMessageDialog(null, "La contraseña no puede contener espacios.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Si pasa todas las comprobaciones, la contraseña es segura
        return true;
    }
    
    public static String encriptarConSHA256(String contraseña) {
        try {
            // Crear un objeto MessageDigest con el algoritmo SHA-256
            MessageDigest digest = MessageDigest.getInstance("SHA-256");

            // Enviar la contraseña al algoritmo de hash y obtener el array de bytes
            byte[] hashBytes = digest.digest(contraseña.getBytes());

            // Convertir el array de bytes a una cadena hexadecimal
            StringBuilder hexString = new StringBuilder();
            for (byte b : hashBytes) {
                // Convertir cada byte a su valor hexadecimal
                String hex = Integer.toHexString(0xff & b);
                // Asegurar que el valor hexadecimal sea de 2 dígitos
                if (hex.length() == 1) {
                    hexString.append('0');
                }
                hexString.append(hex);
            }

            // Retornar el hash en formato hexadecimal
            return hexString.toString();

        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException("Error al encriptar la contraseña", e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Apellidos;
    public javax.swing.JButton BotonRegistrarse;
    public javax.swing.JButton BotonRegistrarse2;
    private javax.swing.JPasswordField Contrasena;
    public javax.swing.JTextField Correo;
    public javax.swing.JLabel Icono_InicioSesion;
    public javax.swing.JTextField Identificacion;
    public javax.swing.JLabel IngresarUsuario;
    public javax.swing.JLabel IngresarUsuario1;
    public javax.swing.JPanel InicioSesion;
    public javax.swing.JPanel InicioSesionFondo;
    public javax.swing.JLabel Titulo_Registrarse;
    public javax.swing.JTextField UsuarioIngresado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
