/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sgpf.views.lote;

/**
 *
 * @author Brayan Hurtado
 */

public class CrearLote extends javax.swing.JFrame {

    /**
     * Creates new form eliminar
     */
    public CrearLote() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaLotes = new javax.swing.JTable();
        LNombre = new javax.swing.JTextField();
        LID = new javax.swing.JTextField();
        LNumCantidad = new javax.swing.JSpinner();
        LEstado = new javax.swing.JTextField();
        LPrecio = new javax.swing.JTextField();
        BotonCrearLote = new javax.swing.JButton();
        BotonActualizarLote = new javax.swing.JButton();
        BotonInforme = new javax.swing.JButton();
        Titulo_InicioSesion = new javax.swing.JLabel();
        Icono_InicioSesion = new javax.swing.JLabel();
        BotonSalirLotes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(100, 149, 237));

        jPanel2.setBackground(new java.awt.Color(100, 149, 237));

        jPanel3.setBackground(new java.awt.Color(0, 204, 255));

        TablaLotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre del lote", "Cod.Identificacion", "Cantidad", "Fecha de vigencia", "Estado"
            }
        ));
        TablaLotes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(TablaLotes);

        LNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        LNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNombreActionPerformed(evt);
            }
        });

        LID.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));
        LID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIDActionPerformed(evt);
            }
        });

        LNumCantidad.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad"));

        LEstado.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado"));
        LEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LEstadoActionPerformed(evt);
            }
        });

        LPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio"));
        LPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LPrecioActionPerformed(evt);
            }
        });

        BotonCrearLote.setBackground(new java.awt.Color(0, 191, 255));
        BotonCrearLote.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BotonCrearLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgpf/resources/icons/farmaco.png"))); // NOI18N
        BotonCrearLote.setText("Crear");
        BotonCrearLote.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BotonCrearLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearLoteActionPerformed(evt);
            }
        });

        BotonActualizarLote.setBackground(new java.awt.Color(0, 191, 255));
        BotonActualizarLote.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BotonActualizarLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgpf/resources/icons/actualizar.png"))); // NOI18N
        BotonActualizarLote.setText("Actualizar");
        BotonActualizarLote.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BotonActualizarLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarLoteActionPerformed(evt);
            }
        });

        BotonInforme.setBackground(new java.awt.Color(0, 191, 255));
        BotonInforme.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BotonInforme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgpf/resources/icons/informe-medico.png"))); // NOI18N
        BotonInforme.setText("Informe");
        BotonInforme.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BotonInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInformeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(BotonCrearLote, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(BotonActualizarLote)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addComponent(LNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LPrecio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LEstado, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LNumCantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(BotonInforme)))
                .addGap(19, 19, 19))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(LNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LNumCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(LPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCrearLote)
                    .addComponent(BotonActualizarLote)
                    .addComponent(BotonInforme))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Titulo_InicioSesion.setFont(new java.awt.Font("Arial Black", 1, 28)); // NOI18N
        Titulo_InicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        Titulo_InicioSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo_InicioSesion.setText("<html>\n<div style=\"text-align: center;\">\nCreacion de Lotes\n</div>\n</html>");

        Icono_InicioSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgpf/resources/icons/Creacion de lotes.png"))); // NOI18N

        BotonSalirLotes.setBackground(new java.awt.Color(0, 191, 255));
        BotonSalirLotes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BotonSalirLotes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgpf/resources/icons/cerrar-sesion.png"))); // NOI18N
        BotonSalirLotes.setText("Salir");
        BotonSalirLotes.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BotonSalirLotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirLotesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(Titulo_InicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(BotonSalirLotes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Icono_InicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Titulo_InicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Icono_InicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(BotonSalirLotes)
                        .addGap(77, 77, 77))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LNombreActionPerformed

    private void LIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LIDActionPerformed

    private void LEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LEstadoActionPerformed

    private void LPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LPrecioActionPerformed

    private void BotonCrearLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonCrearLoteActionPerformed

    private void BotonActualizarLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonActualizarLoteActionPerformed

    private void BotonInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInformeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonInformeActionPerformed

    private void BotonSalirLotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirLotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonSalirLotesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearLote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonActualizarLote;
    public javax.swing.JButton BotonCrearLote;
    public javax.swing.JButton BotonInforme;
    public javax.swing.JButton BotonSalirLotes;
    public javax.swing.JLabel Icono_InicioSesion;
    private javax.swing.JTextField LEstado;
    private javax.swing.JTextField LID;
    public javax.swing.JTextField LNombre;
    public javax.swing.JSpinner LNumCantidad;
    private javax.swing.JTextField LPrecio;
    private javax.swing.JTable TablaLotes;
    public javax.swing.JLabel Titulo_InicioSesion;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
