/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sgpf.views.lote;

import java.text.SimpleDateFormat;
import sgpf.models.Medicamento;
import sgpf.views.MainForm;
import java.util.List;
import javax.swing.JOptionPane;
import sgpf.daos.LoteDao;
import sgpf.daos.MedicamentoDao;
import sgpf.views.login.InicioSesion;

/**
 *
 * @author Brayan Hurtado
 */

public class CrearLote extends javax.swing.JFrame {

    private MedicamentoDao medicamentoDao;

    /**
     * Creates new form eliminar
     */
    public CrearLote() {
        initComponents();
        medicamentoDao = new MedicamentoDao();
        llenarComboBoxMedicamentos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        LNombre = new javax.swing.JTextField();
        LNumCantidad = new javax.swing.JSpinner();
        BotonCrearLote = new javax.swing.JButton();
        jComboBoxMedicamentos = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        Titulo_InicioSesion = new javax.swing.JLabel();
        Icono_InicioSesion = new javax.swing.JLabel();
        BotonSalirLotes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(100, 149, 237));

        jPanel2.setBackground(new java.awt.Color(100, 149, 237));

        jPanel3.setBackground(new java.awt.Color(0, 204, 255));

        LNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        LNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNombreActionPerformed(evt);
            }
        });

        LNumCantidad.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad"));

        BotonCrearLote.setBackground(new java.awt.Color(0, 191, 255));
        BotonCrearLote.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BotonCrearLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgpf/resources/icons/farmaco.png"))); // NOI18N
        BotonCrearLote.setText("Crear");
        BotonCrearLote.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BotonCrearLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearLoteActionPerformed(evt);
            }
        });

        jComboBoxMedicamentos.setBorder(javax.swing.BorderFactory.createTitledBorder("Medicamento"));

        jDateChooser1.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de Vencimiento"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxMedicamentos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LNumCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonCrearLote, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(312, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(LNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LNumCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(BotonCrearLote)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Titulo_InicioSesion.setFont(new java.awt.Font("Arial Black", 1, 28)); // NOI18N
        Titulo_InicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        Titulo_InicioSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo_InicioSesion.setText("<html>\n<div style=\"text-align: center;\">\nCreacion de Lotes\n</div>\n</html>");

        Icono_InicioSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgpf/resources/icons/Creacion de lotes.png"))); // NOI18N

        BotonSalirLotes.setBackground(new java.awt.Color(0, 191, 255));
        BotonSalirLotes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BotonSalirLotes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgpf/resources/icons/cerrar-sesion.png"))); // NOI18N
        BotonSalirLotes.setText("Salir");
        BotonSalirLotes.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BotonSalirLotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirLotesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(Titulo_InicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(BotonSalirLotes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Icono_InicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Titulo_InicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Icono_InicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(BotonSalirLotes)
                        .addGap(77, 77, 77))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LNombreActionPerformed

    private void BotonCrearLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearLoteActionPerformed
        String nombre = LNombre.getText().trim();
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo 'Nombre' no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que la cantidad sea mayor a 0
        int cantidad = (Integer) LNumCantidad.getValue();
        if (cantidad <= 0) {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a 0.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que se haya seleccionado una fecha y que sea válida
        java.util.Date fechaVencimiento = jDateChooser1.getDate();
        if (fechaVencimiento == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha de vencimiento.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        java.util.Date fechaActual = new java.util.Date();
        if (fechaVencimiento.before(fechaActual)) {
            JOptionPane.showMessageDialog(this, "La fecha de vencimiento debe ser posterior a la fecha actual.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que se haya seleccionado un medicamento
        if (jComboBoxMedicamentos.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un medicamento.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Si todas las validaciones pasan, mostrar un mensaje de éxito (o proceder con la lógica)
        String medicamento = jComboBoxMedicamentos.getSelectedItem().toString();
        JOptionPane.showMessageDialog(this, "Lote creado exitosamente:\n" +
                "Nombre: " + nombre + "\n" +
                "Cantidad: " + cantidad + "\n" +
                "Medicamento: " + medicamento + "\n" +
                "Fecha de vencimiento: " + fechaVencimiento, "Éxito", JOptionPane.INFORMATION_MESSAGE);

        Medicamento medicamentoSeleccionado = (Medicamento) jComboBoxMedicamentos.getSelectedItem();
        int medicamentoId = medicamentoSeleccionado.getIdMedicamento(); // Asegúrate de que el objeto Medicamento tenga un método getId()

        // Convertir la fecha de vencimiento a String en el formato adecuado
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String fechaVencimientoStr = sdf.format(fechaVencimiento);

        // Si todas las validaciones pasan, mostrar un mensaje de éxito (o proceder con la lógica)
        JOptionPane.showMessageDialog(this, "Lote creado exitosamente:\n" +
                "Nombre: " + nombre + "\n" +
                "Cantidad: " + cantidad + "\n" +
                "Medicamento: " + medicamentoSeleccionado.getNombre() + "\n" +
                "Fecha de vencimiento: " + fechaVencimientoStr, "Éxito", JOptionPane.INFORMATION_MESSAGE);

        LoteDao loteDAO = new LoteDao();
        boolean exito = loteDAO.crearLote(nombre, cantidad, medicamentoId, fechaVencimientoStr);

        if (exito) {
            JOptionPane.showMessageDialog(this, "Lote registrado con éxito en la base de datos.", "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
            MainForm mainForm = new MainForm();
            mainForm.setVisible(true); 
            this.dispose(); 
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar el lote en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonCrearLoteActionPerformed
  
    private void BotonSalirLotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirLotesActionPerformed
       MainForm mainForm = new MainForm();
       mainForm.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BotonSalirLotesActionPerformed

    private void llenarComboBoxMedicamentos() {
        try {
            // Obtener todos los medicamentos
            List<Medicamento> medicamentos = medicamentoDao.obtenerTodos();

            // Vaciar el JComboBox para evitar datos duplicados
            jComboBoxMedicamentos.removeAllItems();

            // Llenar el JComboBox con los objetos Medicamento
            for (Medicamento medicamento : medicamentos) {
                jComboBoxMedicamentos.addItem(medicamento);  // Agregar el objeto Medicamento completo
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar medicamentos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearLote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonCrearLote;
    public javax.swing.JButton BotonSalirLotes;
    public javax.swing.JLabel Icono_InicioSesion;
    public javax.swing.JTextField LNombre;
    public javax.swing.JSpinner LNumCantidad;
    public javax.swing.JLabel Titulo_InicioSesion;
    private javax.swing.JComboBox<Medicamento> jComboBoxMedicamentos;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
